### ISSUE TITLE
Webdriverio v8 errors resolving dependencies

### ISSUE THREAD

**Issue by Nemesischild** [webdriverio-community/wdio-cucumberjs-json-reporter#102]
**Describe your question with as much detail as possible**
noticed that the peer dependency is set to  @wdio/cucumber-framework@"7.x" in the package.json
This means i am getting hard failures and  "ERESOLVE unable to resolve dependency tree" error when trying to install along side Webdriverio v8 (8.0.0-alpha.365). 

**If it's about a specific piece of code, try and include some of it to support your question.**
As you can see the webdriverio versions included int eh main branch package.json are below the versions i am using 
```json
[ "dependencies": {
    "@cucumber/gherkin": "~22.0.0",
    "@wdio/logger": "~7.16.0",
    "@wdio/reporter": "~7.16.13",
    "fs-extra": "~10.0.0",
    "strip-ansi": "^6.0.1",
    "webdriverio": "~7.16.13"
  },
  "peerDependencies": {
    "@wdio/cucumber-framework": "7.x"
  },
  "devDependencies": {
    "@types/fs-extra": "^9.0.13",
    "@types/jest": "^27.4.0",
    "@types/long": "^4.0.1",
    "@types/node": "^15.14.9",
    "@typescript-eslint/eslint-plugin": "^4.33.0",
    "@typescript-eslint/eslint-plugin-tslint": "^4.33.0",
    "@typescript-eslint/parser": "^4.33.0",
    "@wdio/types": "^7.16.13",
    "babel-eslint": "^10.1.0",
    "babel-plugin-transform-function-bind": "^6.22.0",
    "coveralls": "^3.1.1",
    "cucumber-messages": "^8.0.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsdoc": "^36.1.1",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-tslint": "^3.1.0",
    "husky": "^7.0.4",
    "jest": "^27.4.7",
    "release-it": "^14.12.3",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.4.0",
    "tslint": "^6.1.3",
    "typescript": "^4.5.4",
    "yargs": "^17.3.1"
  },]
```

**Environment (please complete the following information):**
 - **Node.js version:** v16.17.0
 - **NPM version:** 8.15.0
 - **webdriver.io version:** 8.0.0-alpha.365
 - **@wdio/cucumber-framework version:** 8.0.0-alpha.365
 - **wdio-cucumberjs-json-reporter version:** 4.4.3

**Additional context**
I noticed there was a previous issue (https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/issues/81) which is resolved but that specifically seems to be forcing a version of the framework that is causing the conflict as it it lower than 8. 

Is it possible to tweak this in someway to enable me to successfully run an npm install and not get the dependency error?

**Comment by christian-bromann** [comment]
The service needs to be tests in a v8 environment before we can release a version that includes `v8` as compatible versions. If you like to help us with that please do. Thank you!

**Comment by sankalpguptasymphony** [comment]
Can we upgrade the V8 dependency please - 

npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cucumber-framework@"7.x" from wdio-cucumberjs-json-reporter@4.4.3

**Comment by christian-bromann** [comment]
@sankalpguptasymphony you are welcome to raise a PR 😉

**Comment by sankalpguptasymphony** [comment]
> @sankalpguptasymphony you are welcome to raise a PR 😉

I am not sure if I am not knowledgeable enough to do it but I'll give it a try once I am able to make Webdriverio 8 work for me.

**Comment by wswebcreation** [comment]
I'm already working on it. I'm first updating all deps for V7 then will work on V8 support

**Comment by PavanMudigonda** [comment]
I happened to have same issue. please help !

**Comment by wswebcreation** [comment]
@PavanMudigonda 

I'm already working on it in [this](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/pull/113) PR, but all help is welcome

**Comment by Nemesischild** [comment]
@wswebcreation / @christian-bromann - I am happy to be guinea pig on this if you have a version ready for testing on a running v8 set up

**Comment by christian-bromann** [comment]
@Nemesischild would you be open to take @wswebcreation PR and bring it over the goal line?

**Comment by arjunk613** [comment]
Unable to deploy in Jenkin due to below error. Can you please help 
While resolving: wdio-cucumberjs-json-reporter@4.4.3
[ERROR] npm ERR! Found: @wdio/cucumber-framework@8.6.9
[ERROR] npm ERR! node_modules/@wdio/cucumber-framework
[ERROR] npm ERR!   dev @wdio/cucumber-framework@"^8.5.6" from the root project

**Comment by dlitmano** [comment]
it is because you are using the newest version webdriverio with old cucumber json reporting

**Comment by jelugbo** [comment]
@christian-bromann / @wswebcreation , I pulled the feat/support-v8 branch and made some changes. Also tested on my local WDIO v8 setup. Are you able to review this?

**Comment by Prabhs2** [comment]
Any updates on how "CucumberJS JSON Reporter" compatible with with WDIO - v8?

**Comment by christian-bromann** [comment]
I will release v5 with support for WebdriverIO v8. Please test it and let me know if any errors occur.

**Comment by Prabhs2** [comment]
Sure, Thank you for the update. That will be very helpful.

**Comment by hegdesgsg** [comment]
@christian-bromann I tried upgrading to v5; however, after the upgrade while running the scripts I am getting below error 

Failed launching test session: Error: Couldn't find plugin "cucumberjs-json" reporter, neither as wdio scoped package "@wdio/cucumberjs-json-reporter" nor as community package "wdio-cucumberjs-json-reporter". Please make sure you have it installed!
[0-0]     at initialisePlugin (file:///Users/<user>/<project_name>/node_modules/@wdio/utils/build/initialisePlugin.js:36:11)
[0-0]     at async BaseReporter._loadReporter (file:///Users/<user>/<project_name>/node_modules/@wdio/runner/build/reporter.js:178:30)
[0-0]     at async Promise.all (index 1)
[0-0]     at async BaseReporter.initReporters (file:///Users/<user>/<project_name>/node_modules/@wdio/runner/build/reporter.js:23:27)
[0-0]     at async Runner.run (file:///Users/<user>/<project_name>/node_modules/@wdio/runner/build/index.js:68:9)
[0-0] FAILED

**Comment by Prabhs2** [comment]
[@christian-bromann](https://github.com/christian-bromann) I tried upgrading to v5; however, after the upgrade while running the scripts I am getting below error

Failed launching test session: Error: Couldn't find plugin "cucumberjs-json" reporter, neither as wdio scoped package "@wdio/cucumberjs-json-reporter" nor as community package "wdio-cucumberjs-json-reporter". Please make sure you have it installed!
[0-0] at initialisePlugin (file:///Users//<project_name>/node_modules/@wdio/utils/build/initialisePlugin.js:36:11)
[0-0] at async BaseReporter._loadReporter (file:///Users//<project_name>/node_modules/@wdio/runner/build/reporter.js:178:30)
[0-0] at async Promise.all (index 1)
[0-0] at async BaseReporter.initReporters (file:///Users//<project_name>/node_modules/@wdio/runner/build/reporter.js:23:27)
[0-0] at async Runner.run (file:///Users//<project_name>/node_modules/@wdio/runner/build/index.js:68:9)
[0-0] FAILED

**Comment by sankalpguptasymphony** [comment]
@christian-bromann Thanks for the upgrade.
I am getting below error while running it, this file is not present in node modules.

Error: Cannot find module '..\node_modules\wdio-cucumberjs-json-reporter\dist\reporter.js'. Please verify that the package.json has a valid "main" entry

**Comment by christian-bromann** [comment]
I just pushed a patch with a fix and released it. Please let me know. Feel free to raise PRs with improvements at any time.
