### ISSUE TITLE
Confusing logging statement: INFO wdio-multiple-cucumber-html-reporter: The 'reportFilePerRetry' was not set, it has been set to the default 'true'

### ISSUE THREAD

**Issue by olbonc01** [webdriverio-community/wdio-cucumberjs-json-reporter#112]
**Environment (please complete the following information):**
 - **Node.js version:** 16.14.1
 - **NPM version:** 8.5.0
 - **webdriver.io version:** [e.g. 5.11.0]
 - **@wdio/cucumber-framework version:** 7.27
 - **wdio-cucumberjs-json-reporter version:** 7.28

**Describe the bug**
The log statement refers to the old wdio-multiple-cucumber-html-reporter:
```INFO wdio-multiple-cucumber-html-reporter: The 'reportFilePerRetry' was not set, it has been set to the default 'true'```

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Snapshots**
If applicable, add snapshots to help explain your problem.

**Additional context**
Change this line: https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/blob/768b04d2761bab7a5101cde15fe381b933f1adc2/lib/reporter.ts#L23
from 
```
const log = logger( 'wdio-multiple-cucumber-html-reporter' );
```
to
```
const log = logger( 'wdio-cucumberjs-json-reporter );
```

**Comment by wswebcreation** [comment]
Thanks for logging this, it will be fixed in the next release that will support V8
