### ISSUE TITLE
Error thrown when filtering out scenarios execution with tagExpression

### ISSUE THREAD

**Issue by salvag-ntt** [webdriverio-community/wdio-cucumberjs-json-reporter#118]
**Environment (please complete the following information):**
 - **Node.js version:** v16.13.0
 - **NPM version:** v9.1.2
 - **webdriver.io version:** 7.0
 - **@wdio/cucumber-framework version:** 8.2.3
 - **wdio-cucumberjs-json-reporter version:** 4.4.2

**Config of webdriver.io and the reporter**
```
reporters: [
    'spec',
    [
      'cucumberjs-json',
      {
        jsonFolder: './test/acceptance/results/',
        language: 'en',
        disableHooks: true,
      },
    ],
  ],
```

**Describe the bug**
When running Webdriver.io test scenarios (multiple feature files containing multiple scenarios with tags) with something like:
`wdio run test/acceptance/conf/wdio.local.conf.ts --cucumberOpts.tagExpression=@personal-info-check` 
then I get the following error
```
[0-0] 2023-03-02T14:10:55.615Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot convert undefined or null to object
[0-0]     at hasOwnProperty (<anonymous>)
[0-0]     at Metadata.determineMetadata (/home/gr4ce/workspace/cyber/node_modules/wdio-cucumberjs-json-reporter/lib/metadata.ts:16:73)
[0-0]     at CucumberJsJsonReporter.onRunnerStart (/home/gr4ce/workspace/cyber/node_modules/wdio-cucumberjs-json-reporter/lib/reporter.ts:96:62)
[0-0]     at CucumberJsJsonReporter.<anonymous> ([/home/gr4ce/workspace/cyber])(file:///home/gr4ce/workspace/cyber//node_modules/wdio-cucumberjs-json-reporter/node_modules/@wdio/reporter/build/index.js:59:18)
[0-0]     at CucumberJsJsonReporter.emit (node:events:390:28)
[0-0]     at CucumberJsJsonReporter.emit (node:domain:475:12)
[0-0]     at file:///home/gr4ce/workspace/cyber//node_modules/@wdio/runner/build/reporter.js:47:56
[0-0]     at Array.forEach (<anonymous>)
[0-0]     at BaseReporter.emit (file:///home/gr4ce/workspace/cyber/node_modules/@wdio/runner/build/reporter.js:47:25)
[0-0]     at Runner._shutdown (file:///home/gr4ce/workspace/cyber/node_modules/@wdio/runner/build/index.js:316:28)

```
Interestingly enough, if I don't use the tagExpression option and run basically all the feature files like this

`wdio run test/acceptance/conf/wdio.local.conf.ts`

everything goes ok. 
I suspect the reporter is not aware of the filtering or it's not triggered by the cucumber framework/executor so might not know that some feature files are not executed, hence gets initialized or something like that with undefined or null params

**To Reproduce**
Run the following
```
git clone https://github.com/giuseppe-salvatore/wdio-sample-error-demo.git
cd wdio-sample-error-demo/
# on below two commands you can replace yarn with npm but you get the point... 
# ignore-engines flag was needed for an incompatibility and had to workaround that way
yarn install --frozen-lockfile --ignore-engines
yarn wdio -- --cucumberOpts.tagExpression="@login" # this will exclude one of the feature files from being executed
# also after taking a look at the log try the following as well and see no error reported
yarn wdio
```
**Expected behavior**
No error should occur, unless I have done something wrong in the configuration

**Snapshots**
not applicable

**Additional context**
the above info should be enough, please let me know if you need anything more

**Comment by dlitmano** [comment]
hey, you are using wdio v8. This tool only supports wdio v7 until updates.

**Comment by christian-bromann** [comment]
> * **webdriver.io version:** 7.0
> * **@wdio/cucumber-framework version:** 8.2.3

Also you should not use different major versions of WebdriverIO.

Seems like you have a general set-up issue. Also see https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/issues/102 for updates on this.

**Comment by giuseppe-salvatore** [comment]
Hi @dlitmano @christian-bromann thanks for your reply.
I tried to initialize a new project forcing version 7.x but couldn't find an easy way with `yarn create wdio .` command. 
I also tried by initializing a new project and then forcing back versions as follows 
```
@wdio/local-runner@7.16.0 
@wdio/cucumber-framework@7.16.0 
@wdio/spec-reporter@7.16.0  
@wdio/selenium-standalone-service@7.16.0
```
removing `node_modules/` folder and the `yarn.lock` first

Those packages were installed at the specified version but when executing the command `yarn wdio` I got the error below. Bottom line is, is there an easy way to install WDIO at a specified version if I don't want the latest?

```
$ wdio run ./wdio.conf.ts

2023-03-06T11:07:47.262Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /home/gr4ce/workspace/test/wdio-sample-error-demo2/wdio.conf.ts: Must use import to load ES Module: /home/gr4ce/workspace/test/wdio-sample-error-demo2/wdio.conf.ts
require() of ES modules is not supported.
require() of /home/gr4ce/workspace/test/wdio-sample-error-demo2/wdio.conf.ts from /home/gr4ce/workspace/test/wdio-sample-error-demo2/node_modules/@wdio/config/build/lib/FileSystemPathService.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.

Instead change the requiring code to use import(), or remove "type": "module" from /home/gr4ce/workspace/test/wdio-sample-error-demo2/package.json.

wdio run <configPath>

Run your WDIO configuration file to initialize your tests. (default)
Options:

      --version             Show version number                        [boolean]

////////////////////////////////////////
... skipping the resto of the help ...
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

@wdio/cli (v7.16.0)

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/wdio.conf.ts
require() of ES modules is not supported.
require() of /home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/wdio.conf.ts from /home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/node_modules/@wdio/config/build/lib/FileSystemPathService.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.

Instead change the requiring code to use import(), or remove "type": "module" from /home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/package.json.
    at createErrRequireEsm (/home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/node_modules/ts-node/dist-raw/node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (/home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/node_modules/ts-node/dist-raw/node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (/home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/node_modules/ts-node/src/index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at FileSystemPathService.loadFile (/home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/node_modules/@wdio/config/build/lib/FileSystemPathService.js:21:16)
    at ConfigParser.addConfigFile (/home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/node_modules/@wdio/config/build/lib/ConfigParser.js:40:46)
    at new Launcher (/home/gr4ce/workspace/bt/marketplace/mobius/test/wdio-sample-error-demo2/node_modules/@wdio/cli/build/launcher.js:34:27) {
  code: 'ERR_REQUIRE_ESM'
}

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by christian-bromann** [comment]
> I tried to initialize a new project forcing version 7.x

Why? We only maintain v7 at this point but don't actively work on bug fixes anymore. It is strongly advised to use latest version of WebdriverIO v8.x

**Comment by giuseppe-salvatore** [comment]
@christian-bromann then I am confused about @dlitmano comment

> hey, you are using wdio v8. This tool only supports wdio v7 until updates.

Does that mean I have to wait to get support for wdio v8 for wdio-cucumber-json-reporter?
Also I think I wrongly said in the version list that I was using WDIO 7 whilst I was using WDIO 8... my bad!

**Comment by dlitmano** [comment]
my setup and it works: @giuseppe-salvatore 
(regression every day)
- Node.js version: v16.15.1
- NPM version: v8.11.0
- webdriver.io version: 7.30.1
- @wdio/cucumber-framework version: 7.30.0
- wdio-cucumberjs-json-reporter version: 4.4.3

**Comment by salvag-ntt** [comment]
@dlitmano thanks for your reply. 

Yeah I can confirm that with Webdriver.io v7 (and appropriate dependencies version) everything works fine. I have setup two branches on this repo https://github.com/giuseppe-salvatore/wdio-sample-error-demo.git `wdio-v7` and `wdio-v8` in case it might help for debugging and future support. If I get the chance I might spend some time debugging it myself.
For now I guess I will use WDIO v7 in my projects and wait until we get support for V8

Just one quick question... when we refer to Webdriver.io version, what we really mean is the @wdio/cli right? I am asking because in other projects I have seen `webdriverio` as a dependency, so was wondering what's the connection between the two

Anyway, thanks for your support and answers, even if the bug was closed quite early

**Comment by christian-bromann** [comment]
> Does that mean I have to wait to get support for wdio v8 for wdio-cucumber-json-reporter?

You can also get involved and help us get support for v8 in place. I think @wswebcreation is a bit overwhelmed with work and won't be able to get to it. Take #113 as inspiration. Any PRs are welcome and very much appreciated.

> so was wondering what's the connection between the two

WebdriverIO package versions are not pinned to each other, so as long as the major version number matches, you should be good to go. I recommend though to always use latest version.

**Comment by salvag-ntt** [comment]
hi @christian-bromann I know this bug is closed but I was wondering if Webdriver.io 8 supports a way to generate cucumber.json report format natively without using an external reporter?

**Comment by syamphaneendra** [comment]
hi @christian-bromann I agree with @giuseppe-salvatore. Though we have few options to generate html report from cucumber jsons, we have only one option generating cucumber json files. 
Do we have any other options for generating cucumber json files.

**Comment by syamphaneendra** [comment]
Hi @giuseppe-salvatore @christian-bromann It worked fine when we use the latest version of **wdio-cucumberjs-json-reporter** which is **5.1.4** and the error is gone.
Thank you both.
