### ISSUE TITLE
Sometimes JSON files generated empty or not full JSON generated (5 and higher versions only)

### ISSUE THREAD

**Issue by HannaTarasevich** [webdriverio-community/wdio-cucumberjs-json-reporter#163]
**Environment (please complete the following information):**
 - **Node.js version:** [18.16.0]
 - **NPM version:** [9.5.1]
 - **webdriver.io version:** [8.10.4]
 - **@wdio/cucumber-framework version:** [8.10.4]
 - **wdio-cucumberjs-json-reporter version:** [5.1.4]

**Config of webdriver.io and the reporter**
  reporters: ['spec','dot', [ 'cucumberjs-json', {
    jsonFolder: './reports/json-output-folder',
    language: 'en',
  }]],

**Describe the bug**
My tests are running on Azure pipelines. After switching from 4.4.3 version to 5.1.4 some expected JSON-results are not added to created JSON-report files (only file with [title].json is created) in ./reports/json-output-folder folder. On 4.4.3 version this JSON files are generated as usual (other package versions are the same). My tests are running using 4 instances and with multiple hooks. I'm not able to reproduce it locally. it looks like JSON-file stops hearing from the worker. So, my methods trying to path.resolve('./reports/json-output-folder', 'title.json') and it's failed with error "Unexpected end of JSON input".

JSON-file can be totally empty, or can be fulfilled with not full JSON (like being cut in the middle of the body).

**To Reproduce**
Unfortunately, there is no stable logic for reproduction.

**Expected behavior**
It is expected to form JSON-files fully (as it's working on 4.4.3 version).

**Comment by christian-bromann** [comment]
@HannaTarasevich do you think you can create a reproducible exampel?

**Comment by HannaTarasevich** [comment]
@christian-bromann I tried my best, but it looks really weird. No logs here, that something went wrong, just the same feature file is ok with 4.4.3, but not working with 5.x.x versions. If I finally find some exact repro logic, I'll definetely add it here.

**Comment by HannaTarasevich** [comment]
@christian-bromann I investigated further and I would like to switch to the approach with fs-extra back on onRunnerEnd. I tested also async pathExist and it has the same issue for me (under the hood it uses fs.accept as well). The suggested approach works totally fine. Could you please take a look?
https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/pull/164

**Comment by christian-bromann** [comment]
Let's continue convo in #164
