### ISSUE TITLE
Control characters (like \t, \n, ....) not properly handled

### ISSUE THREAD

**Issue by joao-motork** [webdriverio-community/wdio-cucumberjs-json-reporter#440]
**Environment (please complete the following information):**
 - **Node.js version:** v20.7.0
 - **NPM version:** 10.1.0
 - **webdriver.io version:** 8.30.0
 - **@wdio/cucumber-framework version:** 8.30.0
 - **wdio-cucumberjs-json-reporter version:** 5.2.0
 - **multiple-cucumber-html-reporter:** 3.6.2

**Describe the bug**
Attaching control characters (like \t, \n, ....) as text/plain and not handle properly and, then, they do not are displayed on the HTML report created from the json.

**Actual result**
Check this example:
![image](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/assets/132624270/c4a053c6-b678-47c6-830e-76d13132892d)

This is what we see now after creating the HTML report:
![image](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/assets/132624270/9602b30b-0197-453b-8644-f07a2a2d51fb)

**Expected result**
This is what I expect to see:
![image](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/assets/132624270/b03a4b7c-19f8-47e4-80bc-b0340a2606ef)

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by joao-motork** [comment]
@christian-bromann I created this PR with the fix: 
https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/pull/441

**Comment by christian-bromann** [comment]
Merged! Will trigger a release. Thanks for the contribution.
