### ISSUE TITLE
Using Soft Assertion in WDIO

### ISSUE THREAD

**Issue by Joothi** [webdriverio-community/wdio-cucumberjs-json-reporter#479]
Hi,

Can anyone suggest, how to use soft assert in WDIO.

My scenario is I am validating around 50 fields, if the 5th field doesn't match WDIO is skipping other and proceeding with other scenario. 

But I need that step to fail and continue to next step. This can achieved in Selenium with Java but I am not sure In Type script.

It would be great if someone support. 

Thanks in advance.

**Comment by christian-bromann** [comment]
Duplicate of https://github.com/webdriverio/expect-webdriverio/issues/227
