### ISSUE TITLE
The "Line" field in the result file .json generated after execution, does not match with the line of  .feature file

### ISSUE THREAD

**Issue by Gomezjh** [webdriverio-community/wdio-cucumberjs-json-reporter#53]
**Environment (please complete the following information):**
 - **Node.js version:** [14.16]
 - **NPM version:** [6.14.11]
 - **webdriver.io version:** [7.5.3]
 - **@wdio/cucumber-framework version:** [7.5.3]
 - **wdio-cucumberjs-json-reporter version:** [2.0.4"]

**Config of webdriver.io and the reporter**
   reporters: [
        'spec',
        
        [ 'cucumberjs-json', {
            jsonFolder: '.tmp/new/',
            language: 'en',
        },
        ],

        ['allure', {
            outputDir: './tests/reports/allure-results',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
        }],
    ],
    cucumberOpts: {
        backtrace: false,
        requireModule: ['@babel/register'],
        failAmbiguousDefinitions: true,
        failFast: false,
        ignoreUndefinedDefinitions: false,
        names: [],
        snippets: true,
        source: true,
        profile: [],
        require: [
            './tests/steps/*.js',
        ],
        scenarioLevelReporter: false,
        order: 'defined',
        snippetSyntax: undefined,
        strict: true,
        // <string> (expression) only execute the features or scenarios with
        // tags matching the expression, see
        // https://docs.cucumber.io/tag-expressions/
        tagExpression: 'not @Pending',
        // <boolean> add cucumber tags to feature or scenario name
        tagsInTitle: false,
        timeout: 720000,
    },

**Describe the bug**
The "Line" field in the result file .json generated after execution, does not match with the line of  .feature file. 

**To Reproduce**
1. Create a .feature file with one or more scenarios, outline scenarios, or some scenarios with te same background
2. Run the created .feature
3. Compare the ""Line" field of the steps in the results file generated with the line of the steps in .feature file

Feature Example:
 
Feature: New Feature
    As a User
    In order to use the App
    I want to be able to login into App 

    Scenario: Correct credentials 
        Given I am in the login screen of the App
        When I login with correct credentials
        Then I see the onboarding

**Expected behavior**
In the results file generated:
 "Given" step should to have "Line" : 7
"When" step should to have "Line" : 8
"Then" step should to have "Line" : 9

**Snapshots**
![image](https://user-images.githubusercontent.com/49615026/118040777-49c19880-b372-11eb-9e56-9de89360f97d.png)

**Additional context**
The snapshot is a simple Scenario, I tried with multiple scenarios in one feature, with outline scenarios, with Background keyword etc etc.

**Comment by wswebcreation** [comment]
@Gomezjh 

I've been checking this, but it seems to be coming from `@wdio/cucumber-framework`, not from this module

See also [this](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/blob/main/lib/reporter.js#L317)

Can you please check there?

Closing this for now
