### ISSUE TITLE
Support for    webdriverio v9.0.4 (2024-08-19)

### ISSUE THREAD

**Issue by nair-sumesh** [webdriverio-community/wdio-cucumberjs-json-reporter#582]
Hi,
On my local project , I upgraded the dependencies as stated below:
```cmd
npx npm-check-updates -u
```
![image](https://github.com/user-attachments/assets/33ac4d59-4b0c-4bd2-8332-3733da98913c)

```cmd
rm -rf package-lock.json && rm -rf node_modules && npm install
```

![image](https://github.com/user-attachments/assets/9bc60725-061f-4074-a111-53a1e0fbfb31)

# Error
Could not resolve dependency:
peer @wdio/cucumber-framework@"^8.0.0" from wdio-cucumberjs-json-reporter@5.2.1
node_modules/wdio-cucumberjs-json-reporter
wdio-cucumberjs-json-reporter@"5.2.1" from the root project

**Comment by christian-bromann** [comment]
Can you provide a description of what this should entail? Raising an issue without description is a bit short.

**Comment by nair-sumesh** [comment]
updated

> Can you provide a description of what this should entail? Raising an issue without description is a bit short.

**Comment by christian-bromann** [comment]
Thank you. Any contributions would be appreciated!

**Comment by HannaTarasevich** [comment]
Hi @christian-bromann,
Please take a look at https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/pull/583

**Comment by Sven-Seyfert** [comment]
Hi folks 👋 ,

did I get it right? In PR #583 was the fix provided, but was not merged, right?
Was the PR incomplete? I really want to contribute here, but I have to understand what should be done.

As long as @wdio/cucumber-framework is not **completly** updated to v9.0.z, it's not possible to use v9 in case this dependency is involved, correct? Please folks, give me a hint and I do my best to support by an PR 😇 .

Thanks.

Best regards
Sven

**Comment by seanpoulter** [comment]
> Hi folks 👋 ,

Hi Sven!

>  Was the PR incomplete? I really want to contribute here, but I have to understand what should be done.

If I understand correctly on the thread for #583, the PR was incomplete and the author didn't have a chance to continue working on it. If you review the comments you should be able to open a new PR.

**Comment by HannaTarasevich** [comment]
Hi folks,
@christian-bromann, kindly take a look https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/pull/608.
