### ISSUE TITLE
Set tsconfig target to 2019

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-cucumberjs-json-reporter#61]
fixes webdriverio/webdriverio#7139

**Comment by vdrulerz** [comment]
@wswebcreation Hi ....can you please see the feasibility of updating the target to 2019 as stated by Christian above??

Thanks much in advance !

**Comment by christian-bromann** [comment]
@vdrulerz feel free to propose a PR.

**Comment by osmolyar** [comment]
@christian-bromann , is there any suggestion as to where the tsconfig target needs to be set to 2019?  Setting the overall automation project's tsconfig target to "es2019" still results in the same error (as in 
https://github.com/webdriverio/webdriverio/issues/7139)

**Comment by erwindetesters** [comment]
I don't think the target should be es2019 but the lib should be.

The target should be es5 so that the output is compatible.
The lib tells TypeScript that you want support for newer syntax.

**Comment by erwinheitzman** [comment]
I don't think the target should be `es2019` but the lib should be.

The `target` should be `es5` so that the output is compatible.
The `lib` tells TypeScript that you want support for newer syntax so this can be set to `es2019`.

**Comment by nextlevelbeard** [comment]
Still experiencing the same problem with either `es5` or `ES2019` as `target`.

**Comment by osmolyar** [comment]
@christian-bromann , is there any suggestion as to where the tsconfig target needs to be set to 2019?  Setting the overall automation project's tsconfig target to "es2019" still results in the same error (as in 
https://github.com/webdriverio/webdriverio/issues/7139)

> 
> 
> Still experiencing the same problem with either `es5` or `ES2019` as `target`.

Same here despite setting both 'target' and 'lib' to 'es5', 'es6', 'es2019' or 'es2020'.  Removing the "?." notation locally does fix the error, at least for now.

**Comment by erwinheitzman** [comment]
I managed to reproduce this locally with NodeJS v12.19.1 and pure Javascript. The reason this is happening is because the code is compiled to es2019 compatible javascript. As you can read here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining optional chaining was introduced with es2019, however Optional chaining in NodeJS is only supported since version 13 and up. This is the reason why I said that just to be safe es5 is most widely used so that no one is experiencing issues.

**Comment by osmolyar** [comment]
Have tried the following:

- With original node v12.9.0, setting reporter package tsconfig target to es6 (or original es2020) => same error, with local project target and lib set to es6 and/or es2019

- Upgraded node to v13.12.0 (same error, with above combinations of reporter package and local project)

- Upgraded node to v14.17.0.  Error with optional chaining syntax doesn't occur, but we have a dependency on a library that doesn't support v14 yet.  A different error also occurs in reporter.ts line 226.

**Comment by christian-bromann** [comment]
Just released `v4.1.0` with a fix for this. Please let me know if it works.

**Comment by osmolyar** [comment]
Yup, it works now!    (Recompiling with target node 12 in tsconfig causes the reporter.js dist file not to contain the optional chaining, apparently.)
