### ISSUE TITLE
Element for the feature itself is output to feature elements, with empty steps array

### ISSUE THREAD

**Issue by osmolyar** [webdriverio-community/wdio-cucumberjs-json-reporter#68]
**Environment (please complete the following information):**
 - **Node.js version:** [12.9.0]
 - **NPM version:** [ 6.14.4]
 - **webdriver.io version:** [7]
 - **@wdio/cucumber-framework version:** [7.0.7]
 - **wdio-cucumberjs-json-reporter version:** [4.1.1]

**Config of webdriver.io and the reporter**
 ```
 [
            'cucumberjs-json',
            {
                jsonFolder: 'testResults',
                language: 'en'
            },
        ],
```

**Describe the bug**
The reporter outputs an element representing the feature itself to the elements array of the feature with this command in the onSuiteStart handler: .

        if (typeof this.report.feature.elements !== 'undefined'  ) {
            this.report.feature.elements.push(this.getScenarioDataObject(payload, this.report.feature.id));
        }

This results in an element with type="scenario" and keyword="Feature", which has an empty steps array.  An empty steps array is not supported by some test management systems, such as Zephyr Scale and QMetry,  and causes the results to fail to upload.

To prevent outputting a feature 'element' representing the feature, suggest limiting the calls of this.getScenarioDataObject to payload.type="scenario", as follows: 

    //edit condition so as not to output an element for the feature itself to the feature's elements
        if (typeof this.report.feature.elements !== 'undefined' && payload.type =="scenario" ) {
            this.report.feature.elements.push(this.getScenarioDataObject(payload, this.report.feature.id));
        }

**To Reproduce**
Generate report for any feature

**Expected behavior**
Do not output elements with empty steps array

**Comment by wswebcreation** [comment]
Thanks submitting an issue @osmolyar 

Do you want to take a stab at it and create a PR?

**Comment by osmolyar** [comment]
> Thanks submitting an issue @osmolyar
> 
> Do you want to take a stab at it and create a PR?

Sure

**Comment by wswebcreation** [comment]
Will be fixed in a new version which will be released this week

**Comment by wswebcreation** [comment]
I've release https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/releases/tag/v4.1.4 can you please test and let me  know of if it now works

**Comment by osmolyar** [comment]
Looks good, thank you!
