### ISSUE TITLE
Step "line" parameter returns blank

### ISSUE THREAD

**Issue by osmolyar** [webdriverio-community/wdio-cucumberjs-json-reporter#70]
**Environment (please complete the following information):**
 - **Node.js version:** [12.9.0]
 - **NPM version:** [ 6.14.4]
 - **webdriver.io version:** [7]
 - **@wdio/cucumber-framework version:** [7.0.7]
 - **wdio-cucumberjs-json-reporter version:** [4.1.1]

**Config of webdriver.io and the reporter**
 ```
 [
            'cucumberjs-json',
            {
                jsonFolder: 'testResults',
                language: 'en'
            },
        ],
```

**Describe the bug**

All steps (other than "Before" and "After") have a blank "line" attribute, as seen in the below sample result.

The following calculation of "line" in getStepDataObject() seems completely incorrect:

` line: parseInt(stepData.uid.substring(title.length, stepData.uid.length), 10) || '',`

The title.length and stepData.uid.length are numbers which should not have anything to do with each other, e.g.
[0-9] stepData.uid 19
[0-9] title.length 73
[0-9] stepData.uid.substring(title.length, stepData.uid.length:
[0-9] parseInt(stepData.uid.substring(title.length, stepData.uid.length), 10) :NaN

Not quite sure what "line" is supposed to represent here (step number??) but the current code results in the value "", which is not supported by QMetry's cucumber json result uploading API. 

```
	{
						"arguments": [],
						"keyword": "Given",
						"name": "I attempt to log into the application as user _SYSTEM with password SYS true",
						"result": {
							"status": "passed",
							"duration": 13070000000
						},
						"line": "",
						"match": {
							"location": "can not be determined with webdriver.io"
						}
					},
					{
						"arguments": [],
						"keyword": "Then",
						"name": "I confirm the page title is Home as expected true",
						"result": {
							"status": "passed",
							"duration": 1243000000
						},
						"line": "",
						"match": {
							"location": "can not be determined with webdriver.io"
						}
					},
					{
						"arguments": [],
						"keyword": "And",
						"name": "the text Welcome to the Management Portal appears on the page",
						"result": {
							"status": "passed",
							"duration": 978000000
						},
						"line": "",
						"match": {
							"location": "can not be determined with webdriver.io"
						}
					},
```
				

**To Reproduce**
Produce report for any feature file

**Expected behavior**
step.line should not be blank

**Additional context**
Current output causes QMetry's cucumber json result output to fail.

**Comment by wswebcreation** [comment]
Thanks @osmolyar

I need to dive into this to, not sure what is allowed according to the official docs. The problem is that I don't have a lot of time currently to work on this so any help would be appreciated

**Comment by osmolyar** [comment]
It turns out that the QMetry's issue is that it expects a number or null for "line", hence gets tripped up by the empty string.  It does not actually use the value.  So perhaps for now the calculation can simply be defaulted to null instead of empty string.

**Comment by wswebcreation** [comment]
I'll default this to `null` for all `line` props. Will fix this in a new release this week

**Comment by osmolyar** [comment]
It works, thank you!  (QMetry also made a change to their REST API to not parse the "line" attribute, just as an fyi)
