### ISSUE TITLE
Handling of cjson:metadata relies on extension capability to be returned by remote end

### ISSUE THREAD

**Issue by mhanysz** [webdriverio-community/wdio-cucumberjs-json-reporter#73]
**Is your feature request related to a problem? Please describe.**
While debugging and fixing an issue with passing custom metadata to the reporter (see https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/issues/66), I noticed that some devices still do not show the correct metadata. I dug further into the problem and noticed, that the reporter works on the _provided capabilities_ from the _remote end_, and not on the _requested capabilities_ from the _local end_. That means, the whole handling of `cjson:metadata` and all other _extension capabilities_ heavily depends on whether the _remote end_ puts them into the _provided capabilities_ or not. My project uses browserstack as the _remote end_ and they do put the _extension capabilities_ into the _provided capabilities_ for MOST of their devices, but not for all. All devices that do not "forward" the _extension capabilities_ in the _provided capabilities_ have the wrong metadata in the end.

**Describe the solution you'd like**
In general, it might be a good idea to pull the cjson:metadata from the _requested capabilities_ and not from the _provided capabilities_, since the `cjson:metadata` capability isn't supposed to be handled by the _remote end_ anyway. This way the plugin wouldn't have to rely on the _remote end_ to forward the _extension capabilities_.

In the code it looks like it would only be a matter of accessing `data.config.capabilities` (which seems to contain the _requested capabilities_) instead of `data.capabilities` (which seems to contain the _provided capabilities_) in the method `Metadata.determineMetadata(data)` to get `cjson:metadata`.

Terms that relate to the w3c webdriver capabilities specification are written in _italics_ to clarify that I refer to these concepts.

**Comment by wswebcreation** [comment]
Think I fixed it, will release a new version this week

**Comment by mhanysz** [comment]
Yes the issue is fixed and the requested capabilities are used now to obtain the cjson:metadata.

The only thing that works different than I expected is, that the explicitly provided metadata gets overridden by the automatically detected ones. For example, when I specify a browser version of "94", then it gets overridden by the automatically detected version " 94.0.992.31". I would expect that the version the user of the plugin explicitly specifies gets precedence over the automatically detected version. If I want the automatically detected version in the report, I'd just not specify it in cjson:metadata.

**Comment by wswebcreation** [comment]
Hi @mhanysz 
You're welcome. What would be the reason to overwrite the provided version if the actual version can be determined?

**Comment by mhanysz** [comment]
The main reason for overriding the automatic detection is, that the reports get shipped to the customer, who may refer to the browser versions by different terms, such as "embedded", "latest" or "LTS". Same goes for Mac OS versions, where the non numerical names are preferred, such as "Mojave" instead of "10.14".

I might be mistaken here, but I thought the main reason for having the option to specify cjson:metadata explicitly was to customize what shows up in the report. And if the auto detection is sufficient for the use case, setting cjson:metadata isn't required at all.

**Comment by wswebcreation** [comment]
Hmm, good point, can you file a new ticket for that. I need to check when I can work on that one

**Comment by mhanysz** [comment]
Done -> https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/issues/75
