### ISSUE TITLE
Loosen peer dependency version of "@wdio/cucumber-framework", to avoid conflicts and enable users to update

### ISSUE THREAD

**Issue by dietergeerts** [webdriverio-community/wdio-cucumberjs-json-reporter#79]
**Is your feature request related to a problem? Please describe.**
I needed to update "@wdio/cucumber-framework" as a bug was solved in it. But now it's not compatible anymore with this package, as it has a very restricting peer dependency on it. 

```
"@wdio/cucumber-framework": "~7.13.2"
```

**Describe the solution you'd like**
I don't see why this would be the case, bit if there is a good reason, it would be helpful to state this reason, as it might lead to not using this package if we can't deal with that reason. If there isn't a specific reason, I would like to see this fixed, so we can update our packages to fix some bugs.

**Describe alternatives you've considered**
Adding a quick fix to our `pnpmfile`.

**Additional context**
N/A

**Comment by christian-bromann** [comment]
@dietergeerts thanks for filing an issue!

I believe we can set this peerdependency to `"@wdio/cucumber-framework": "^7.13.2"`. Mind raising a PR?

**Comment by wswebcreation** [comment]
Fixed with version https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/releases/tag/v4.3.1
