### ISSUE TITLE
could not resolve dependency

### ISSUE THREAD

**Issue by fogrizovic** [webdriverio-community/wdio-cucumberjs-json-reporter#81]
**Environment (please complete the following information):**
 - **Node.js version:** v16.13.0
 - **NPM version:** 8.1.0
 - **webdriver.io version:** 7.16.14
 - **@wdio/cucumber-framework version:** 7.16.14
 - **wdio-cucumberjs-json-reporter version:** 4.2.0

**Describe the bug**
Getting the following error when doing npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: wdio@1.0.0
npm ERR! Found: @wdio/cucumber-framework@7.16.14
npm ERR! node_modules/@wdio/cucumber-framework
npm ERR!   dev @wdio/cucumber-framework@"^7.16.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cucumber-framework@"~7.13.2" from wdio-cucumberjs-json-reporter@4.2.0
npm ERR! node_modules/wdio-cucumberjs-json-reporter
npm ERR!   dev wdio-cucumberjs-json-reporter@"^4.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by wswebcreation** [comment]
Fix with version https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/releases/tag/v4.3.1
