### ISSUE TITLE
Capture the hook name in the json report, which is a new feature of cucumber-js

### ISSUE THREAD

**Issue by dietergeerts** [webdriverio-community/wdio-cucumberjs-json-reporter#94]
**Is your feature request related to a problem? Please describe.**
When creating E2E test reports, all hooks have an empty name, which can be hard in debugging.

**Describe the solution you'd like**
The @cucumber/cucumber package has done an update and added a feature to add a hook name. It would be great if this name gets into the json report, so that the html report can on his turn use it further.
https://github.com/cucumber/cucumber-js/issues/1079#issuecomment-1103628005

**Describe alternatives you've considered**
There isn't an alternative for this. Before, it just wasn't possible, now it is.

**Additional context**
Currently, this is a report we get, to make clear how difficult it can be when one fails and need to find out which one. (this is the html report from a reporter that uses the json result from this reporter. I checked, and the name isn't filled in.)
![image](https://user-images.githubusercontent.com/7393706/167107458-30e17d64-d4a2-4280-a88d-1523b12bce65.png)

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that implement this are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by qaflorent** [comment]
From what I investigated, it seems that the issue doesn't come from this package. I looked in [wdio-cucumber-framework](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-cucumber-framework) and investigations leaded me to an issue already logged to https://github.com/webdriverio/webdriverio/issues/8324

So it confirms that you won't have the name yet in json report and that it should be solve out of this package.

**Comment by christian-bromann** [comment]
Awesome 🎉
