### ISSUE TITLE
Incorrect type for attach argument

### ISSUE THREAD

**Issue by FrancisTaylor** [webdriverio-community/wdio-cucumberjs-json-reporter#99]
**Environment (please complete the following information):**
 - **Node.js version:** v14.19.1.
 - **NPM version:** 6.14.16
 - **webdriver.io version:** 7.19.7
 - **@wdio/cucumber-framework version:** 7.19.7
 - **wdio-cucumberjs-json-reporter version:** 4.4.1

**Config of webdriver.io and the reporter**

**Describe the bug**

excerpt from reporter.ts:

export class CucumberJsJsonReporter extends WDIOReporter {
   ...
    public static attach ( data: string, type = TEXT_PLAIN ): void {
   ...

excerpt from README.md:

...
cucumberJson.attach({"json-string": true}, 'application/json');
...

**To Reproduce**

Attempt to use the example code yields an error:

Argument of type '{ hello: string; }' is not assignable to parameter of type 'string'.

**Expected behavior**
example code should work

**Snapshots**

**Additional context**

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any contributions that resolves the bug are highly appreciated. Let us know if you have any questions. Cheers!

**Comment by FrancisTaylor** [comment]
This fix is crude but it works for me:

*** wdio-cucumberjs-json-reporter-orig/lib/models.ts    Wed Jul  6 07:02:18 2022
--- wdio-cucumberjs-json-reporter-main/lib/models.ts    Tue Aug  2 13:38:51 2022
***************
*** 96,107 ****
  }

  export interface CucumberJsAttachment {
!     data: string;
      type: string;
  }

  export interface Embedding {
!     data: string;
      mime_type: string;
  }

--- 96,107 ----
  }

  export interface CucumberJsAttachment {
!     data;
      type: string;
  }

  export interface Embedding {
!     data;
      mime_type: string;
  }

diff -r -C 3 wdio-cucumberjs-json-reporter-orig/lib/reporter.ts wdio-cucumberjs-json-reporter-main/lib/reporter.ts
*** wdio-cucumberjs-json-reporter-orig/lib/reporter.ts  Wed Jul  6 07:02:18 2022
--- wdio-cucumberjs-json-reporter-main/lib/reporter.ts  Tue Aug  2 13:34:52 2022
***************
*** 56,62 ****
      /**
       * Attach data to the report
       */
!     public static attach ( data: string, type = TEXT_PLAIN ): void {
          // eslint-disable-next-line @typescript-eslint/ban-types
          ( process.emit as Function )( 'wdioCucumberJsReporter:attachment', { data, type } );
      }
--- 56,62 ----
      /**
       * Attach data to the report
       */
!     public static attach ( data, type = TEXT_PLAIN ): void {
          // eslint-disable-next-line @typescript-eslint/ban-types
          ( process.emit as Function )( 'wdioCucumberJsReporter:attachment', { data, type } );
      }

**Comment by christian-bromann** [comment]
@wswebcreation what do you think?

**Comment by wswebcreation** [comment]
I can take a look at it today and fix it

**Comment by wswebcreation** [comment]
Released https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/releases/tag/v4.4.2

**Comment by FrancisTaylor** [comment]
This is not fixed in 4.4.2

The method signature for the attach method still has the data parameter as type string, so the example code still fails to compile.

**Comment by FrancisTaylor** [comment]
Perhaps it is prudent to have test cases for documented examples...

**Comment by FrancisTaylor** [comment]
This is not fixed, see my latest comment in bug #99.

**Comment by christian-bromann** [comment]
@FrancisTaylor mind raising a PR with the missing fixes?

**Comment by FrancisTaylor** [comment]
I am unfamiliar with github workflow.

Here is the missing fix: reporter.ts, line 59:

Original:

    public static attach ( data: string, type = TEXT_PLAIN ): void {

My fix:
    public static attach ( data, type = TEXT_PLAIN ): void {

I am also unfamiliar with your internal code policy so I don’t know the correct way to fix this, whether to completely ditch the type specifier or to use some other type.

Anyway I made the brash assumption that your example code would work and now I have coded myself into depending on it, there is no other way to accomplish my task.   Maybe you can also add a test, as a fellow test developer I cannot stress enough the importance of having test cases for published examples, our customers depend on the accuracy of our documentation.  Can you please fix this ASAP.  This is now blocking my whole team.

Thanks.

**Comment by christian-bromann** [comment]
> Can you please fix this ASAP. This is now blocking my whole team.

As a fellow open source developer I would say, get involved into the project rather than demanding to fix things ASAP. A quick internet tutorial will help and we are here if you have questions. The world as you describe it is lovely but we only have so much free time to work on these projects for free so you don't have to pay a dime to use them.

I suggest the following change:

```patch
- public static attach ( data: string, type = TEXT_PLAIN ): void {
+ public static attach ( data: any, type = TEXT_PLAIN ): void {
```

as I can not really tell the restrictions to the data type upstream the code.

**Comment by wswebcreation** [comment]
Ahh, crap, I changed the models, but not this code.

will see if I can squeeze it in tomorrow, will go on vacation 😅

**Comment by FrancisTaylor** [comment]
I am sorry if you interpreted ‘can you please’ as a demand, I assumed that you would be alarmed about the documentation discrepancy; in our organization, such a situation would be considered a crisis.  I am also sorry that you did not understand that the “Possible” in ASAP is your judgement.  I would also perhaps hope that you would note that this is my very first github bug report (I have just inherited the lead position of a rather large testing project, of which this is a very small piece), so what you are seeing here is my ‘get involved in the project’.  As things ramp up and skill levels improve, my team may request enhancements and it is my intention to develop these enhancements internally and share them with you.  I am sorry to have gotten off on the wrong foot with you, I hope we can move forward without conflict.

- Fran

PS  I have an idea for an enhancement request, I don’t know how it would work, maybe you could suggest something?  Anyway we are feeding this data into a database and searching on it, our search engine uses backslash as an escape character, so searching for backslash characters is problematic.  We are running tests on multiple platforms including windows and so we have paths with both forward and backward slashes, a mess for searching.  We would like the reporter to be able to run the data through a filter that can remove or substitute such problematic data (in this case we would replace backslashes with slashes).  We are currently filtering the data on the receiving end, but the server is CPU bound so it would be better to do the filtering on the producer.  Perhaps it could be implemented as a “chained” setup where a ‘filter’ reporter passes the data to another reporter?  Or maybe just a hook proc to do the filtering?  I don’t know enough about the reporter design to know what is possible or feasible.  I would like to learn more and work through the concept so I can file a proper enhancement request.

**Comment by wswebcreation** [comment]
@FrancisTaylor 

I've released a new version, see https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/releases/tag/v4.4.3. This should now properly fix it.

I totally understand the _sentiment_ behind this, but a team is never blocked by a type that is not correct. A temporary workaround is to use the beloved/behated `//@ts-ignore`  in your code.

As @christian-bromann mentioned, we all do this in our spare time, trying to help the testing community. If you love to learn more about this or want to contribute then please let us know. We're not only here to provide you with code, but also with some time to help you and your team fix this yourselves 😄. 

Regarding your request, this is not something that would fit in the scope of this project, but....., WebdriverIO wouldn't be as awesome if it didn't had a solution for this.
You can create a filter in the `onComplete`-hook where you would read the dir you use to write the JSON files to, and parse every file (not as a JSON but text file),  replace all  backslashes with slashes and write the data again.

Hope this helps
